version: "3"

services:
  coordinator:
    image: registry.mixlab.mondcarion.group/mix-coordinator:latest
    networks:
    - mixnet
    volumes:
    - ./coordinator.json:/opt/app/coordinator.json
    command: "coordinator.json"
  mix0:
    image: registry.mixlab.mondcarion.group/mix-node:latest
    ports:
    - "8888:8888"
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "14689490706445660689531739089290021008940504028808418022674106323036"
  mix1:
    image: registry.mixlab.mondcarion.group/mix-node:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "20815161192604671013523738980898559822441853889016438091067546813119"
  mix2:
    image: registry.mixlab.mondcarion.group/mix-node:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "21490961561964975616985684726550966802671830914349170474172887400339"
  dead-drop:
    image: registry.mixlab.mondcarion.group/mix-dead-drop:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
  client:
    image: registry.mixlab.mondcarion.group/mix-client:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    command: "dead-drop 8888 hello this is obi wan"
    depends_on:
    - coordinator
    - mix0
    - mix1
    - mix2

networks:
  mixnet:
