version: "3"

services:
  coordinator:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-coordinator:latest
    networks:
    - mixnet
  gateway:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-gateway:latest
    ports:
    - "8888:8888"
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "gateway 8000 8001"
  relay:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-relay:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "relay 8001 8002"
  dead-drop:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-dead-drop:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "dead-drop 8003"
  client1:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-client:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    command: "1111 i have the high ground!"
    depends_on:
    - coordinator
    - gateway
    - relay
    - dead-drop
  client2:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-client:latest
    networks:
      - mixnet
    volumes:
      - ./coord.json:/opt/app/coord.json
    command: "1111"
    depends_on:
      - coordinator
      - gateway
      - relay
      - dead-drop
  client3:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-client:latest
    networks:
      - mixnet
    volumes:
      - ./coord.json:/opt/app/coord.json
    command: "2000"
    depends_on:
      - coordinator
      - gateway
      - relay
      - dead-drop
  interactive-client:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-client:latest
    networks:
      - mixnet
    volumes:
      - ./coord.json:/opt/app/coord.json
      - ./interactive-client/run.sh:/opt/app/run.sh
    entrypoint: /bin/sh
    depends_on:
      - coordinator
      - gateway
      - relay
      - dead-drop

networks:
  mixnet:
