version: "3"

services:
  coordinator:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-coordinator:latest
    networks:
    - mixnet
  mixa:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-mix:latest
    ports:
    - "8888:8888"
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "mixa"
  mixb:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-mix:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "mixb"
  mixc:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-mix:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    depends_on:
    - coordinator
    command: "mixc"
  dead-drop:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-dead-drop:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
  client:
    image: registry.mixlab.mondcarion.group/latte-mixxiato-client:latest
    networks:
    - mixnet
    volumes:
    - ./coord.json:/opt/app/coord.json
    command: "dead-drop 8888 hello this is obi wan"
    depends_on:
    - coordinator
    - mixa
    - mixb
    - mixc

networks:
  mixnet:
