stages:
  - build
  - test
  - deploy
  - post-deploy

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# This template uses jdk17 for verifying and deploying images
image: maven:3.8.5-eclipse-temurin-17

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build:jdk17:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS package"
  artifacts:
    paths:
      - "target/"
      - "client/target/"
      - "coordinator/target/"
      - "lib/target/"
      - "gateway/target/"
      - "relay/target/"
      - "dead-drop/target/"
    expire_in: "30 days"

containers:jdk17:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build:jdk17
  script:
    - 'sh .ci/build-containers.sh'

release:jdk17:
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy"
  artifacts:
    paths:
      - "target/"
  rules:
    - if: $CI_COMMIT_TAG